### PR TITLE
Fix : add navigation icon + title

### PR DESCRIPTION
**Pull request by ravenfeld**
I noticed a difference between the SC and SCEE screens.
It's missing : 
the navigation icon
the title

By the way, I've removed the unnecessary spacing provided by PreferenceScreen.

Screenshot_20240929_074152

### CODE REVIEW

**Comment by mnalis** [comment]
Have you seen https://github.com/Helium314/SCEE/issues/640#issuecomment-2334651604 (and below)?

**Comment by Helium314** [comment]
Are you 100% sure I will not have more issues when merging upstream? This happend already 3 times in the past months, and dealing with this over and over again simply seems like a waste of time.

**Comment by ravenfeld** [comment]
I didn't see the way out, sorry.
I don't know exactly what problems you had with the fusion.
So to solve the merging problem you don't have to put the fragment extension in an SC file, you can move it and make a FragmentExtScee.kt file. 

After that, the best thing to do is to compose them as you mentioned in the issue.

**Comment by Helium314** [comment]
> So to solve the merging problem you don't have to put the fragment extension in an SC file, you can move it and make a FragmentExtScee.kt file.

But this is still time _I_ have to spend on this temporary fix, instead of just working on other things. And I notice how the time I can / want to spend on SCEE is reducing recently, now that it doesn't work any more on my main phone.

**Comment by ravenfeld** [comment]
Yes, it's temporary, because for me it's time to switch to compose.

What's wrong with your phone?
Maybe I can help you fix it.

**Comment by Helium314** [comment]
> What's wrong with your phone?

See https://github.com/maplibre/maplibre-native/issues/2206
I doubt you can help... either with MapLibre, or with convincing some phone manufacturer to produce some reasonable replacement for S4 Mini.

Anyway, so I'll give this one more try, but if I run into merge conflicts again because of the title, I'm going to remove it and will not accept another PR for this.

**Pull request merged**
