### PR TITLE
Error during one of some GPX

### PR DESCRIPTION
**Pull request by ravenfeld**
I've noticed that the GPX import doesn't work very well because it doesn't take enough cases.

I've been using the 'com.github.ticofab:android-gpx-parser' lib for several years now, which I find works very well.

So I set it up to retrieve the points for the GPX import. 

If you don't want an external lib, we can write the xml parser by hand.

### CODE REVIEW

**Comment by Helium314** [comment]
I'm ok with a library, but
* when we use it, other uses of "hand parsing" could also be replaced (if worth the effort, e.g. for writing gpx notes the compatibility is not really an issue as the format is clear)
* SC already has functionality of uploading gpx files with notes, which apparently does not use this library. Maybe you could do parsing the same way.

**Comment by ravenfeld** [comment]
I've looked at their "GpxTrackParser" file to see if it's the one you're talking about. 
If so, it only works for their answer because the code corresponds to what it receives.
We can't use it like that.
We have to make our own, and as a result I've found it more "complicated". 

Then we can make our parser by trying to use their "XmlParser" file to try and make code close to their parser.

**Comment by Helium314** [comment]
Thanks, then let's just stick with the library.
Is there any other SCEE-thing where you think GPX parsing should be improved?

btw please avoid unrelated formatting changes, this just makes the diff harder to read.

**Comment by ravenfeld** [comment]
I'd say maybe suggest changing the color, the very light green I found hard to differentiate at first but it's just a detail. Adding the option to choose the color requires a bit of code and I don't know how many people use the import.

>btw please avoid unrelated formatting changes, this just makes the diff harder to read.
Sorry when I save it formats the file and I didn't pay attention when I commented that lines outside my scope had been taken.

**Comment by Helium314** [comment]
I don't want to bother with anything on visual details, as it will need to be re-done anyway after merging the MapLibre PR.

**Comment by ravenfeld** [comment]
If you need any help with mapLibre, don't hesitate. I know it well enough to have done a project where I ported a lot of stuff to maplibre.

**Comment by Helium314** [comment]
The main issues are in https://github.com/streetcomplete/StreetComplete/pull/5693:
Sometimes parts of overlays are disappearing, which seems to be a MapLibre bug (but if you have a workaround, or it's something else, your help would be more than welcome).
And there is the crash on my main phone, which at least is being worked on.

**Comment by mcliquid** [comment]
I've never tried this function but I just downloaded a GPX file from komoot and tried to import it but the file is gray and not selectable in the file list. Is this related here? 🧐

**Comment by Helium314** [comment]
No, this is related to
https://github.com/Helium314/SCEE/blob/3a5021a030776ee3ee043513b99a7ef7eeeeb917/app/src/main/java/de/westnordost/streetcomplete/screens/settings/DisplaySettingsFragment.kt#L62-L65
Maybe your phone can correctly identify gpx tracks and thus does not use the generic octet stream?

Maybe the type can be omitted if necessary, so every file is allowed.

**Pull request merged**
