### PR TITLE
Add other answer "Tree is stump"

### LINKED ISSUE #622: "Uhh..." -> "It's a tree stomp now" on tree leave type/species quest
**Use case**
Sometimes trees get cut down and when you pass them, you see just a tree stomp left. 

**Proposed Solution**
Would be nice to have an easy way to answer this in the tree leave type/species quest, instead of having to switch to the tag view and edit there tags manually. 

**Screenshot**

Screenshot_2024-08-26-20-50-17-408-edit_de westnordost streetcomplete expert

### PR DESCRIPTION
**Pull request by mnalis**
- Fixes https://github.com/Helium314/SCEE/issues/622

Seems to work for both the `Does this tree have needles or leaves?` and for `What is the genus or species of this tree?`. 

Independent test would be welcome though (as I had some guessing how it works for _genus_ quest); there is debug APK (which can be installed alongside normal SCEE release) available for download [here](https://github.com/mnalis/StreetComplete/actions/runs/10607174129) if @RubenKelevra or someone else wants to try it out.

### CODE REVIEW

**Comment by mnalis** [comment]
put to Draft status again; waiting for answer in https://github.com/streetcomplete/StreetComplete/issues/5852 so PR can be split if first half is wanted in StreetComplete too

**Comment by mnalis** [comment]
StreetComplete part has been implemented in https://github.com/streetcomplete/StreetComplete/pull/5853; when SCEE is synced with StreetComplete master, I can resolve conflicts and cleanup this PR.

Or this PR can merged as is, and conflict (extra argument to `applyAnswer`) resolved when merging StreetComplete to SCEE. Perhaps that second option makes more sense?

**Comment by RubenKelevra** [comment]
> there is debug APK (which can be installed alongside normal SCEE release) available for download [here](https://github.com/mnalis/StreetComplete/actions/runs/10607174129) if @RubenKelevra or someone else wants to try it out.

Checked and works flawlessly for me. Thanks!

**Comment by mnalis** [comment]
Cleaned up the small merge conflict after SC version was merged to SCEE master; this PR should be fine for merging now. 

_(note however that build of current SCEE master [fails](https://github.com/mnalis/StreetComplete/actions/runs/10710280605/job/29696715110), but that seems to be unrelated to this PR)_

**Pull request merged**
