### PR TITLE
New Quest: sac_scale

### PR DESCRIPTION
**Pull request by ravenfeld**
Hello, I've just discovered your work and it's great, it's exactly what I was missing.

I'd like to contribute at my level and add a few quests.

It starts with the sac scale.

I don't know how you manage thongs because I haven't seen them in other PRs, so I'll be happy to let you explain.

For the moment I've chosen to go without photos because I didn't want to scroll, but I can add them. 

I don't know where you find the icons either, so I've taken the one from trail_visibility, but I can try to make one if you don't have an icon base.

I'll be happy to try and help you, I'll go straight to work on the missing French translations ;)

Screenshot_20240630_085855

### CODE REVIEW

**Comment by Helium314** [comment]
The filter _needs_ to be more restrictive or it may easily result in unwanted spam of `sac_scale`.
And this is already where it becomes tricky... maybe surface and access tags can help, but on first glance I doubt it would work good enough.

@mcliquid you were working on a bunch of related quests, like trail visibility. Do you have any idea for a useful restriction of the filter?

**Comment by mcliquid** [comment]
> Do you have any idea for a useful restriction of the filter?

I would at least add a surface filter for all suitable unpaved surfaces like
`and surface ~ "grass|sand|dirt|soil|fine_gravel|compacted|wood|gravel|pebblestone|rock|ground|earth|mud|woodchips|snow|ice|salt|stone"`

`access` tags are difficult here because most hiking paths don't have explicit `hiking=yes`. But tmembership of a route-relation could be included. That would certainly make sense. `route=hiking` and `route= hiking`.

**Comment by ravenfeld** [comment]
In France that's enough, but don't worry about adding the surface area for the relationship, I don't because not everything is a relationship and must have the sac scala.
The problem with the surface area is that many path in France don't have the surface key, so we wouldn't be able to raise the quest because we don't have the surface area.
Imagine a small path next to a relationship and adding the scale bag lets the router know that the path is difficult and that it's better to continue on another path.
maybe :
`and (!surface or surface ~ "grass|sand|dirt|soil|fine_gravel|compacted|wood|gravel|pebblestone|rock|ground|earth|mud|woodchips|snow|ice|salt|stone")`

Then don't worry about adding the filter you want, I'll modify it for my own use afterwards.

**Comment by mcliquid** [comment]
> France don't have the surface key, so we wouldn't be able to raise the quest because we don't have the surface area.

The new SAC scale quest should only be displayed after the surface quest anyway. This means that the user first completes the surface and then, if appropriate, the SAC scale.

**Comment by Helium314** [comment]
Alternatively it could be an overlay. That might even be more suitable for the subjective nature of `sac_scale`, and you can add `sac_scale` without requiring a surface.

**Comment by ravenfeld** [comment]
> > France don't have the surface key, so we wouldn't be able to raise the quest because we don't have the surface area.
> 
> The new SAC scale quest should only be displayed after the surface quest anyway. This means that the user first completes the surface and then, if appropriate, the SAC scale.

That's a good point, it's more my way of doing things where I select a quest when I go out. But if worst comes to worst, I'll just change it for myself.

**Comment by ravenfeld** [comment]
> Alternatively it could be an overlay. That might even be more suitable for the subjective nature of `sac_scale`, and you can add `sac_scale` without requiring a surface.

I think it's very specific, it's more my way of using the application.

I like the fact that you ask for the `surface` and then the `sac_scale`

**Comment by mcliquid** [comment]
Personally, I would like to see pictures, as it generally improves the assessment. Only the text seems very sober.

**Comment by ravenfeld** [comment]
> Personally, I would like to see pictures, as it generally improves the assessment. Only the text seems very sober.

https://wiki.openstreetmap.org/wiki/FR:Key:trail_visibility


Does it really add anything? At worst, for those who are used to using wiki, it can provide a technical memo reference, perhaps?

**Comment by ravenfeld** [comment]
Screenshot_20240701_191205

@mcliquid You're right, even if I think it's not always easy with photos. It's nicer with

**Comment by ravenfeld** [comment]
I've added an icon to stop using the same one as trail_visibility

sac_scale

**Comment by Helium314** [comment]
I'm still very worried the current filter is not enough. Inside Paris, where mountaing hiking is not really a thing, it finds more than 1500 ways eligible for this quest.

**Comment by mcliquid** [comment]
If it were technically possible to check whether the respective path is also integrated in a hiking relation, this would certainly help a lot.

**Comment by ravenfeld** [comment]
The problem is that not everything is about relationships, and we're going to miss out on a lot of them as a result.

For me, it's not just for the mountains, it's for all types of hiking. So yes, we're more used to indicating it when it's at the beginning of the level.

For me it's the same as trail_visibility, so we must have the same reasoning. 
We have to find the best request if there is one ;)

**Comment by ravenfeld** [comment]
For me it's the same as trail_visibility, so we must have the same reasoning. 
We have to find the best request if there is one ;)

**Comment by Helium314** [comment]
Yes, this difficulty is probably why no one attempted to do a `sac_scale` quest.
Checking for hiking relations is possible, but of cource very limiting.
Switching to an overlay would be a solution, but has the usual limitations of overlays.

Some ideas:
* Check whether the way is connected to another way with `sac_scale and sac_scale != hiking`. This should work well (you can edit one way "manually" for starting), but needs work in the scan-for-quests code because when you answer such a quest, the neighboring ways need to be re-checked. SC(EE) is currently not doing this for performance reasons.
* Check for hiking relations by default, but make it so you can disable it in quest settings. This way I would trust that only users who are really interested select this option.

**Comment by ravenfeld** [comment]
I'm going to add looking at whether it's in a hiking relation.
Do you have an example where there's a settings quest, because I'm not sure I understand. 
I was going to modify `preferences_ee_quests.xml`

**Comment by ravenfeld** [comment]
@Helium314 
There's something I don't understand. 
As soon as I add `route = hiking` my filter no longer works, as if the relation + ways doesn't work. However, in the `AddFerryAccessMotorVehicle` file, that's what's there.
Any ideas?

```
override val elementFilter = """
        ways, relations with
          route = hiking
          and highway ~ path
          and !sac_scale
          and ( access !~ no|private or foot ~ yes|permissive|designated or bicycle ~ yes|permissive|designated)
          and (!lit or lit = no)
          and surface ~ "grass|sand|dirt|soil|fine_gravel|compacted|wood|gravel|pebblestone|rock|ground|earth|mud|woodchips|snow|ice|salt|stone"
    """
```

**Comment by HolgerJeromin** [comment]
The AddFerryAccessMotorVehicle quest return relations **and** ways with `route=ferry`. 

Here you want explicit only ways which are part of a relation which this tag which needs a different syntax (not sure if this exists).

**Comment by ravenfeld** [comment]
Thank you very much for your time,
I'll try to dig one out to see if it's possible.
I'm also going to look at an overlay like you indicated for the `mtb:scale` even if I find that it's not the same thing for me.

Overpass sample
```
[out:json][timeout:25];
// gather results


rel["route"="hiking"]({{bbox}});
way(r);
way._["highway"="path"]["sac_scale"!~ "."];


// print results
out geom;
```

**Comment by Helium314** [comment]
For checking ways contained in a route you will need to use a `OsmElementQuestType` instead of an `OsmFilterQuestType`.
This allows to base the element selection on more than a single element. With `getApplicableElements` you have access to nearby elements, which does also includes the routes the way is part of.
You could find all hiking routes in the `mapData`, and then return all `highway=path and !sac_scale and ...` that are member of one of those relations.

Best check some existing quests and the documentation for `OsmElementQuestType`, often you can use them to get ideas.

**Comment by Helium314** [comment]
> Do you have an example where there's a settings quest, because I'm not sure I understand.

Quest settings are used e.g. in `AddLevel`. You need to set `hasQuestSettings = true` and return an `AlertDialog` that allows setting whatever you need in `getQuestSettingsDialog`.

**Comment by ravenfeld** [comment]
> > Do you have an example where there's a settings quest, because I'm not sure I understand.
> 
> Quest settings are used e.g. in `AddLevel`. You need to set `hasQuestSettings = true` and return an `AlertDialog` that allows setting whatever you need in `getQuestSettingsDialog`.

Thank you very much for the pedestrian crossing, I had to look up how to do it and I've now understood. 
I need to understand the relationship now, thanks for the directions.

**Comment by ravenfeld** [comment]
@Helium314 
Thank you very much for the instructions.
I managed to do what you want

- [x] Paths must be in a relationship=hiking
- [x] Add a parameter to deactivate or not the query with the relation=hiking

**Comment by Helium314** [comment]
@ravenfeld do you have an area where the quest is showing up with the default filter?
I would like to test performance of the quest filter, but moving to random mountain areas over the alps always gave me 0 quests. (maybe those areas are too well mapped?)

**Comment by ravenfeld** [comment]
Near me you have this element which has no sac_scale and is in a carfour node relationship.
https://www.openstreetmap.org/way/344603781
Otherwise I'll give you the overpass request that I used to find it because with the addition in a relationship I had a bit of trouble finding it ;) 

```
[out:json][timeout:25];
// gather results


rel["route"="hiking"]({{bbox}});
way(r);
way._["highway"="path"]["sac_scale"!~ "."];


// print results
out geom;
```

I am interested in knowing how to test performance, on Profiler my phone does not go up more than that.

**Comment by Helium314** [comment]
Thanks for the query, that was really helpful!
Performance is definitely nothing to worry about, pretty much the same as other simple quests.

A few things still should be done:
* Better use _SAC_ scale in the title
* add images / author / license to authors.txt
* make the images much smaller to be in line with other images of the same size (e.g. via ferrate scale images are ~50 kB for xxhdpi)

**Comment by mcliquid** [comment]
> make the images much smaller to be in line with other images of the same size (e.g. via ferrate scale images are ~50 kB for xxhdpi)

I don't have write access here, but I reduced the image size while increasing the quality:
[reduced-images.zip](https://github.com/user-attachments/files/16118668/reduced-images.zip)

**Comment by mcliquid** [comment]
Content for the `app/src/main/res/authors.txt`
```
sac_scale_t1.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T1.jpg
sac_scale_t2.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T2.jpg
sac_scale_t3.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T3.jpg
sac_scale_t4.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T4.jpg
sac_scale_t5.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T5.jpg
sac_scale_t6.jpg            (C) Marco Volken      https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T6.jpg
```

**Comment by mcliquid** [comment]
By the way: Nice teamwork here, I really like the drive. Reminds me of previous hackathons :)

**Comment by Helium314** [comment]
Sac -> SAC is still missing in the resource string, as well as licenses for all images and information regarding `sac_scale.svg`.

Also app/src/main/res/drawable/authors.txt seems to be the more appropriate file over res/graphics/authors.txt

**Comment by ravenfeld** [comment]
I couldn't find the authors file you're talking about (` app/src/main/res/drawable/authors.txt`), but I did find this one `app/src/main/res/authors.txt`

**Comment by Helium314** [comment]
Oops, sorry. You found the right file!

There is one thing I hadn't considered an issue until now: The images do not have proper licensing information. I thought OSM wiki images would be fine, but e.g. https://wiki.openstreetmap.org/wiki/File:SAC_SCALE_T1.jpg even has a big warning about this.
Given that the author appears to be a professional photographer (http://www.marcovolken.ch/), I think we are not allowed to use their images just like that. If they choose to enforce their copyright, I would be the one responsible for the violation, and I don't want that risk.

**Comment by ravenfeld** [comment]
You're right, let's take the time to find some free photos.

**Comment by Helium314** [comment]
Sorry for asking this last, it will take a while now until the quest can be merged. But unfontunately is see this as quite important.

**Comment by ravenfeld** [comment]
There's nothing to worry about, it's normal. If the worst came to the worst, I'd go out and take some photos myself ;)

**Comment by mnalis** [comment]
Good news, I've contacted the author at marcovolken.ch and he confirmed that he's indeed contributed those pictures, and that the images are fine CC-BY-SA 4.0 (it is just that back in days the OSM wiki didn't ask for specific licensing). I've updated the wiki accordingly at his request.

**So the images can be used as-is!**

---

Relatedly, he also noted that SAC scale rules have changed a few times since that wiki was created and pointed to https://www.sac-cas.ch/de/ausbildung-und-sicherheit/tourenplanung/schwierigkeitsskalen/ for latest revision, but there is already wiki talk about that at https://wiki.openstreetmap.org/wiki/Talk:Key:sac_scale#SAC_Hiking_Scale_Revision_2023 (with no clear answer what to do about it).

**Comment by Helium314** [comment]
Thanks @mnalis!

> Relatedly, he also noted that SAC scale rules have changed a few times since that wiki was created and pointed to https://www.sac-cas.ch/de/ausbildung-und-sicherheit/tourenplanung/schwierigkeitsskalen/ for latest revision, but there is already wiki talk about that at https://wiki.openstreetmap.org/wiki/Talk:Key:sac_scale#SAC_Hiking_Scale_Revision_2023 (with no clear answer what to do about it).

I haven't looked at the changes / new definition, but from the wiki discussion I would assume the descriptions and images in the quest would still be ok.

**Comment by goldfndr** [comment]
Given the size of the pictures and the size of the text in the screenshot, could the text of the wiki's Trail column values be added into this GUI's choice descriptions (perhaps with a line break and bullets)? Harmful to add? I find the Trail column somewhat more explanatory, but I'll confess I only have experience with T1+T2 and a little of T3, so perhaps this quest isn't for me. The wiki itself has the following line:

*A way may not fit all of the criteria listed below for trail, terrain and requirements. In general, use the greatest difficulty that is matched.*

**Comment by ravenfeld** [comment]
> Given the size of the pictures and the size of the text in the screenshot, could the text of the wiki's Trail column values be added into this GUI's choice descriptions (perhaps with a line break and bullets)? Harmful to add? I find the Trail column somewhat more explanatory, but I'll confess I only have experience with T1+T2 and a little of T3, so perhaps this quest isn't for me. The wiki itself has the following line:
> 
> _A way may not fit all of the criteria listed below for trail, terrain and requirements. In general, use the greatest difficulty that is matched._

Strings can be modified without any problem. I'm waiting until I have the values in weblale before I do it, and it'll be a mix of field and requirement.

**Pull request merged**
