### PR TITLE
Added piste:lit quest

### LINKED ISSUE #491: Is this piste lit? (`piste:lit=yes/no`)
### General
Affected tag(s) to be modified/added: [piste:lit](https://wiki.openstreetmap.org/wiki/Key:piste:lit)
Question asked: **Is this piste lit?**

### Checklist
Checklist for quest suggestions (see [guidelines](https://github.com/Helium314/SCEE/blob/modified/QUEST_GUIDELINES.md)):
- [x] 🚧 To be added tag is established and has a useful purpose
- [x] 🤔 Any answer the user can give should have an equivalent tagging (SCEE quests may not be answerable in all cases, but please keep this rare)
- [x] 🐿️ A survey is necessary (may require knowledge of the subject, though easy answering for everyone is preferred)
- [ ] 💤 Not an overwhelming percentage of quests have the same answer (No spam)
- [x] 🕓 Applies to a reasonable number of map data (Worth the effort)

### Ideas for implementation

**Element selection:** 
```
ways, relations with
          piste:type ~ downhill|nordic|sled|ski_jump|ice_skate
          and !piste:lit
```

**Proposed UI:**
* simple OsmFilterQuestType quest only with Yes / No answers

### PR DESCRIPTION
**Pull request by mcliquid**
Fixes #491

### CODE REVIEW

**Comment by paulklie** [comment]
I cannot add comments in the code so I need to do so here:
https://github.com/Helium314/SCEE/blob/fbca70f3fe9d6a0becd11c687193ed20aad8638e/app/src/main/java/de/westnordost/streetcomplete/quests/piste_lit/AddPisteLit.kt#L18

You check the age of `lit` here. Did you mean to reference `piste:lit`?

**Comment by mcliquid** [comment]
I'm not entirely sure what I was thinking at the time, or if I was thinking at all 🙂 , but today I would say that it makes some sense if the piste is also located on a highway that was once tagged with `lit=*`. If this track has a `lit=yes` that was set over 8 years ago and a `piste:lit=no`, then the quest would check the piste lighting again.
I personally don't know of any slope that would be normally lit as a road/track in summer but not in winter.
Therefore, the entire line can probably be removed. Or it can be kept as a backup for extremely rare cases; in my opinion, it doesn't hurt the Quest.
An (super rare) example where the quest would appear after 8 years: https://www.openstreetmap.org/way/687216388
But then we would have to change `lit` to `lit=yes` I guess.

**Comment by paulklie** [comment]
> I'm not entirely sure what I was thinking at the time, or if I was thinking at all 🙂 , but today I would say that it makes some sense if the piste is also located on a highway that was once tagged with `lit=*`. If this track has a `lit=yes` that was set over 8 years ago and a `piste:lit=no`, then the quest would check the piste lighting again. I personally don't know of any slope that would be normally lit as a road/track in summer but not in winter. Therefore, the entire line can probably be removed. Or it can be kept as a backup for extremely rare cases; in my opinion, it doesn't hurt the Quest. An (super rare) example where the quest would appear after 8 years: https://www.openstreetmap.org/way/687216388 But then we would have to change `lit` to `lit=yes` I guess.

Do you think a user can differentiate between `lit` and `piste:lit`? (I have no idea since I have never been in such a place, just wondering).

**Comment by HolgerJeromin** [comment]
The problem is to explain the users which of the two tags are tagged.
In my experience piste lighting are fundamentally different to highway lighting. More like stadion floodlights.

**Comment by paulklie** [comment]
Now that https://github.com/streetcomplete/StreetComplete/commit/c9e02f828dbd3c13ff4c79b7d33742299e916939 is merged, the lit status of non-highway pistes is asked in SC. I think think quest will need to be revamped to only ask for the highways (and inform the user that we are only interested in piste lighting, not regular street lighting).

**Comment by Helium314** [comment]
> Now that [streetcomplete@c9e02f8](https://github.com/streetcomplete/StreetComplete/commit/c9e02f828dbd3c13ff4c79b7d33742299e916939) is merged, the lit status of non-highway pistes is asked in SC. I think think quest will need to be revamped to only ask for the highways (and inform the user that we are only interested in piste lighting, not regular street lighting).

done

**Pull request merged**
