### PR TITLE
Add new SCEE icon

### PR DESCRIPTION
**Pull request by westnordost**

### CODE REVIEW

**Comment by westnordost** [comment]
store_icon
launcher_foreground_monochrome
ic_launcher_round

**Comment by HolgerJeromin** [comment]
Ref #597

**Comment by Helium314** [comment]
Wow, that's a surprising lot of changed files...
Thanks!

**Comment by westnordost** [comment]
Yeah... thankfully most are auto-generated by that import tool. It is to support all the different API versions that don't support vector + "adaptive" icons.

The only "real" source assets are in `/res/app icon`

**Pull request merged**
