### PR TITLE
Add safe_loops in bicycle_parking quest

### PR DESCRIPTION
**Pull request by mcliquid**
Adding `safe_loops` in the `bicycle_parking` quest (see https://github.com/streetcomplete/StreetComplete/issues/5774)

### CODE REVIEW

**Comment by mnalis** [comment]
<Strike>
Note this part of: https://github.com/streetcomplete/StreetComplete/issues/5774#issuecomment-2288512838 
</strike>

---

Ooops, sorry, I've missed that this PR is for SCEE, not StreetComplete. :sweat_smile: 
Bicycle expertise is fine to be required here IMHO. :+1: 

Have you tested that it works @mcliquid ?

**Comment by mcliquid** [comment]
> Have you tested that it works @mcliquid ?

@mnalis I checked out the quest in the emulator, if that's what you mean. That's part of it for me. I haven't programmed any unit tests, UI tests or anything like that for it, is that only necessary for a new value?

image
image
image
image
image

**Comment by mcliquid** [comment]
@Helium314 Thank you!

**Comment by mnalis** [comment]
> I checked out the quest in the emulator, if that's what you mean

Yes, that's what I've meant. Thanks!

**Pull request merged**
