### PR TITLE
Add sac_scale=strolling to sac_scale quest

### LINKED ISSUE #692: Add sac_scale=strolling to existing quest
Voting passed the proposal to add `sac_scale=strolling`, so I think it should be added to the existing quest asking for hikability.

There is already a photo on the [wiki page](https://wiki.openstreetmap.org/wiki/Key:sac_scale) that should be usable like the rest. Sorry I don't know how to make this change myself.

### PR DESCRIPTION
**Pull request by mcliquid**
Fixes #692 

@mnalis Feel free to check the images as you did before to see if there is more potential for optimization.

@goldfndr You're welcome to propose new strings for the quest.

### CODE REVIEW

**Comment by mnalis** [comment]
Sure... I've uploaded `app/src/main/res/drawable-xxhdpi/sac_scale_strolling.jpg` to https://squoosh.app and with default settings (`MozJPEG` / `quality=75`) it accomplishes significant file size reduction of `40%`, while still looking just fine for the purpose (slight loss of detail in embroidery on women's hat design does not look problematic to me). 

While one could probably push it some more, I think that this initial reduction is quite fine low-hanging fruit. Other resolutions would probably benefit similarly. Can you try @mcliquid ? It has a nice slider so you can easily compare old vs. new in case significant artifacts appear.

**Comment by mcliquid** [comment]
@mnalis I've now reduced the images with squoosh.app. Previously I used tinypng.com as also recommended by you in another PR.

**Comment by ravenfeld** [comment]
Top responsiveness for adding this new tag, which has just been validated.

**Comment by Helium314** [comment]
Thanks!
@goldfndr you can still propose better text, best just open a new issue

**Pull request merged**
